stages:
  - build

buildDocker:
  stage: build
  image: docker:latest
  services:
    - name: docker:20-dind
      alias: docker
      command: ["--tls=false"]
  tags:
    - dind
  variables:
    DOCKER_BUILDKIT: 1
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t reg.sysdevservices.tech/frontend:local .
    - docker tag reg.sysdevservices.tech/frontend:local reg.sysdevservices.tech/frontend:local
    - docker push reg.sysdevservices.tech/frontend:local